---
title: "Causal Inference - The Mixtape Vol. 1"
author: "Jake Johnson"
date: 
output: 
  html_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r cim-pre, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = 'cim_cache/',
  fig.path = 'cim_fig/',
  message = F,
  warning = F
  )
load_tidy()
```

# Figures

## Figure 3

```{r fig03}
set.seed(3)

dat <- tibble(
  x = rnorm(1E4, 0, 1),
  u = rnorm(1E4, 0, 1),
  y = 5.5 * x + 12 * u
  )

reg <- lm(y ~ x, data = dat)

dat %<>% mutate(
  yhat1 = predict(reg),
  yhat2 = 0.0732608 + 5.685033 * x,
  uhat1 = reg$residuals,
  uhat2 = y - yhat2
  )

select(dat, yhat1, yhat2) %>% skim()
select(dat, uhat1, uhat2) %>% skim()

ggplot(dat, aes(x, y)) +
  geom_point() +
  stat_smooth(method = 'lm', col = 'red') +
  labs(title = 'OLS Regression Line') +
  ggthemes::theme_stata()
```

## Figure 4

```{r fig04}
ggplot(dat, aes(yhat1, uhat1)) +
  geom_point() +
  labs(x = 'Fitted Values', y = 'Residuals') +
  ggthemes::theme_stata()
```

## Figure 5

```{r fig05}
set.seed(5)

ols <- function() {
  dat <- tibble(
    x = 9 * rnorm(1E4, 0, 1),
    u = 36 * rnorm(1E4, 0, 1),
    y = 3 + 2 * x + u
    )
  reg <- lm(y ~ x, data = dat)
  coef(reg)['x']
}

beta <- replicate(1E3, ols()) ; skim(beta)

ggplot(tibble(x = beta)) +
  geom_histogram(aes(x)) +
  ggthemes::theme_stata()
```

## Figure 6

```{r fig06}
dat <- read_dta('/Applications/Stata/auto.dta')

# bivariate regression
reg_b <- lm(price ~ length, data = dat)

# multivariate regression
reg_m <- lm(price ~ length + weight + headroom + mpg, data = dat)

# auxiliary regression 1 
reg_a1 <- lm(length ~ weight + headroom + mpg, data = dat)
dat %<>% mutate(length_resid = reg_a1$residuals)

# auxiliary regression 2
reg_a2 <- lm(price ~ length_resid, data = dat)

# check the values
cat(
  coef(reg_m)[['length']],
  coef(reg_a2)[['length_resid']],
  cov(dat$price, dat$length_resid) / var(dat$length_resid)
  )

# shift factor (mean adjustment of length requires adjustment of intercept)
s_factor <- coef(reg_b)['length'] * mean(dat$length)

tibble(
  price = rep(dat$price, 2),
  length = c(dat$length - mean(dat$length), dat$length_resid),
  type = unlist(map(c('BV', 'MV'), rep, times = nrow(dat)))
  ) %>%
  ggplot() +
  geom_point(aes(length, price, colour = type)) +
  scale_colour_manual(values = c('red', 'green')) +
  geom_abline(
    intercept = coef(reg_b)['(Intercept)'] + s_factor,
    slope = coef(reg_b)['length'],
    col = 'red'
    ) +
  geom_abline(
    intercept = coef(reg_a2)['(Intercept)'],
    slope = coef(reg_a2)['length_resid'],
    col = 'green'
    ) +
  labs(title = 'Regression Anatomy', x = 'Length', y = 'Price') +
  ggthemes::theme_stata()
```

## Figure Gender disparities controlling for occupation

```{r figGEN}
library(ggraph)
library(tidygraph)

set.seed(19)

# network
net <- tribble(
  ~from, ~to,
  'A', 'o',
  'A', 'y', 
  'F', 'd',
  'F', 'o',
  'd', 'o',
  'o', 'y',
  )
net %<>% as_tbl_graph(directed = T)
net %<>% 
  activate(edges) %>%
  mutate(
    lty  = c('u', 'u', 'o', 'u', 'o', 'o'),
    lty2 = c('u', 'u', 'o', 'u', 'o', 'o')
    )

ggraph(net, layout = 'kk') +
  geom_edge_link(
    aes(edge_linetyp = lty, linetype = lty), # weird quirk in ggraph 1.0.1.999
    arrow = arrow(length = unit(2, "mm")),
    start_cap = circle(3, "mm"), end_cap = circle(3, "mm")
  ) + 
  geom_node_point() +
  geom_node_text(
    aes(label = name), hjust = -1, vjust = 2
  ) +
  theme_void() +
  theme(legend.position = 'none')
```

# Tables

## Table 6

```{r tab06}
set.seed(6)

dat <- tibble(
  x = 9 * rnorm(10, 0, 1),
  u = 36 * rnorm(10, 0, 1),
  y = 3 + 2 * x + u
  )

reg <- lm(y ~ x, data = dat)

dat %<>% mutate(
  yhat = predict(reg) %>% unname(),
  uhat = reg$residuals %>% unname(),
  x_uhat = x * uhat,
  yhat_uhat = yhat * uhat
  )

out <- rbind(dat, colSums(dat))
out %<>% cbind(tibble(no = c(1:10, 'Sum')), .)
names(out) <- c(
  names(out)[1:4],
  '$\\mathbf{\\hat y}$',
  '$\\mathbf{\\hat u}$',
  '$\\mathbf{\\hat x \\hat u}$',
  '$\\mathbf{\\hat y \\hat u}$'
  )

knitr::kable(
  out,
  align = 'c',
  row.names = F,
  digits = 1,
  format = 'html'
  ) %>%
  kableExtra::row_spec(11, bold = T) %>%
  kableExtra::kable_styling()
```

## Table 8

```{r tab08}
set.seed(8)

# basics
dat <- tibble(
  female = as.numeric(runif(1E4, 0, 1) >= 0.5),
  ability = rnorm(1E4, 0, 1)
  )

# outcomes
#   discrim = all females experience discrimination
#   occupat = ability and discrimination
#     (no discrimintaiton <=> M/F sort the same)
#   wage = ability, discrimination, and occupation
dat %<>%
  mutate(
    discrim = female,
    occupat = 1 + 2 * ability - + 0 * female - 2 * discrim + rnorm(1E4, 0, 1),
    wage = 1 + 2* ability - 1 * discrim + 1 * occupat + rnorm(1E4, 0, 1)
  )

# regressions
#   unconditional effect of discrimination: wage (direct) + occupat (indirect)
#   adding occupation controls for collider!: female -> occupat <- ability
#   correct specification
reg <- list(
  lm(wage ~ discrim, data = dat),
  lm(wage ~ discrim + occupat, data = dat),
  lm(wage ~ discrim + occupat + ability, data = dat)
  )
reg %<>% map_dfr(tidy)

reg$model <- c(
  rep('Biased unconditional', 2),
  rep('Biased', 3),
  rep('Unbiased conditional', 4)
  )

out <- gather(reg, statistic, value, -term, -model) %>%
  filter(statistic %in% c('estimate', 'std.error')) %>%
  mutate(
    value = format(value, digits = 2),
    value = if_else(statistic == 'std.error', str_c('(', value, ')'), value)
  ) %>%
  spread(model, value, fill = '') %>%
  select(-statistic)

out <- out[c(1:2, 5:6, 7:8, 3:4), c(1, 3, 2, 4)]
out[, 1] <- c(
  '(Intercept)', '',
  'Female', '',
  'Occupation', '',
  'Ability', ''
)
names(out)[1] <- c('Covariates:')
out %<>%
  add_row(
    `Covariates:` = 'N',
    `Biased unconditional` = '10,000',
    `Biased` = '10,000',
    `Unbiased conditional` = '10,000'
  )

knitr::kable(
  out,
  align = 'c',
  row.names = F,
  format = 'html'
  ) %>%
  kableExtra::row_spec(9, bold = T) %>%
  kableExtra::kable_styling()
```
