---
title: 'Multilevel structures'
author:
date:
always_allow_html: yes
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r arm11-pre, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = '../arm_cache/',
  fig.path = '../arm_fig/',
  message = F,
  warning = F
  )
library(arm)
load_tidy()

# arm link
arm_url <- 'http://stat.columbia.edu/~gelman/arm/examples/'

# arm functions
walk(list.files('./arm/arm_fun', full.names = T), source)
```

## Question 1

```{r arm11-q01_}
apt <- read.table(str_c(arm_url, 'rodents/apt.dat'))
dis <- read.table(str_c(arm_url, 'rodents/dist.dat'))
```

### (a)

$$
P(y_{ij} = 1) = \text{logit}^{-1} \left( \beta_0  + \beta_1 \times \text{race}_i + \beta_2 \times \text{floor}_i + \beta_3 \times \text{bldg}_i + \alpha_j \right)
$$

### (b)

$$
\begin{align}
P(y_{i} = 1) &= \text{logit}^{-1} \left( \beta_0 + \beta_1 \times \text{race}_i + \beta_2 \times \text{floor}_i + \beta_3 \times \text{bldg}_i + \alpha_{j[i]} \right) \\
\alpha_{j[i]} &\sim N \left( \gamma_0 + \gamma_1 \times \text{defects}_j + \gamma_2 \times \text{poor}_j, \sigma_{\alpha} ^ 2 \right)
\end{align}
$$

## Question 2

Skip

## Question 3

```{r arm11-q03_}
win32 <- read_table2(str_c(arm_url, 'olympics/olympics1932.txt'), skip = 20)
```

### (a)

```{r arm11-q03a}
pro32 <- cbind(1:7, win32[seq(1, 14, by = 2), 3:9])
pro32 %<>% as_tibble()
names(pro32) <- c('pair', str_c('judge_', 1:7))
print(pro32)

per32 <- cbind(1:7, win32[seq(2, 14, by = 2), 2:8])
per32 %<>% as_tibble()
names(per32) <- c('pair', str_c('judge_', 1:7))
print(per32)
```

### (b)

I think there is a typo here in that the output is $49 \times 4$.

```{r arm11-q03b}

# join scores after converting to long
dat <- left_join(
  gather(pro32, judge, score, -pair),
  gather(per32, judge, score, -pair),
  by = c('pair', 'judge')
)

# convert to numeric
dat %<>% 
  mutate(
    judge = str_replace_all(judge, 'judge_', '')
  ) %>%
  mutate_at(vars(score.x, score.y, judge), as.numeric)
  

# add names and rearrange
names(dat)[3:4] <- c('tech', 'perf')
dat <- dat[c(3:4, 1:2)]

# print
print(dat, n = 5)
```

### (c)

```{r arm11-q03c}
dat %<>%
  mutate(
    same = case_when(
      pair == 1 & judge == 5 ~ 1,
      pair == 2 & judge == 7 ~ 1,
      pair == 3 & judge == 1 ~ 1,
      pair == 4 & judge == 1 ~ 1,
      pair == 7 & judge == 7 ~ 1,
      T ~ 0
    )
  )
```

## Question 4

### (a)

Note that in the online documentation it is suggested to consider paitents whose initial age is between one and five.

```{r arm11-q04a}

# load the data
cd4 <- read_csv(str_c(arm_url, 'cd4/allvar.csv'))
cd4 %<>% na.omit()

# filter and add outcome
dat <- cd4 %>%
  filter(baseage >= 1 & baseage <= 5) %>%
  mutate(
    time = visage - baseage,
    treatmnt = treatmnt - 1,
    y = sqrt(CD4PCT)
  ) %>%
  arrange(newpid)

# drop patients with no record of first visit
dat %<>% filter(!newpid %in% c(9, 35, 166))

# plot
p <- ggplot(dat) +
  geom_line(aes(time, y, colour = factor(newpid))) +
  guides(colour = F) +
  facet_wrap(~treatmnt) +
  theme_ipsum()
p
```

### (b)

```{r arm11-q04b}

# plot
p <- ggplot(dat) +
  geom_point(aes(time, y, colour = factor(newpid))) +
  geom_smooth(aes(time, y, colour = factor(newpid)), method = 'lm', se = F) +
  guides(colour = F) +
  facet_wrap(~treatmnt) +
  theme_ipsum()
p
```

### (c)

```{r arm11-q04c}

# step one
reg_a <- list()
for (i in seq_along(unique(dat$newpid))) {
  
  reg_a[[i]] <- lm(
    sqrt(CD4PCT) ~ time,
    data = filter(dat, newpid == unique(dat$newpid)[i])
  )
  
}

# step two
a <- map(reg_a, ~coef(.x)[1]) %>% flatten_dbl()
reg_b <- lm(a ~ treatmnt + baseage, data = filter(dat, VISIT == 1))
print(reg_b)
```
