---
title: 'ARM: Chapter 7'
output: html_document
---

```{r arm07-pre, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = 'arm_cache/',
  fig.path = 'arm_fig/',
  message = F,
  warning = F
  )
library(arm)
load_tidy()
arm_url <- 'http://stat.columbia.edu/~gelman/arm/examples/'
```

### Question 1

#### (a)

```{r arm07-q01a}
shots <- function(p) {
  s <- rbinom(2, 1, p)
  i <- 2
  two_miss = F
  while (!two_miss) {
    if (sum(s[i - 1]:s[i]) == 0) {
      two_miss <- T
    } else {
      s <- append(s, rbinom(1, 1, p))
      i <- i + 1
    }
  }
  list(shots = s, n = length(s))
}
```

#### (b)

```{r arm07-q01b}
shots_sims <- list()
for (s in 1:1000) {
  shots_sims[[s]] <- shots(0.6)
}
n <- map_int(shots_sims, ~.x$n)
mean(n)
sd(n)
qplot(n, bins = 50)
```

#### (c)

```{r arm07-q01c}
dat <- tibble(n = n, makes = map_int(shots_sims, ~sum(.x$shots)))
dat %<>% mutate(success = makes / n)

p <- ggplot(dat) + geom_jitter(aes(n, success))
p
```

### Question 2

```{r arm07-q02}
m <- c(5.13, 0.17)
f <- c(4.96, 0.20)
x <- 1750

cable <- function(people, male = m, female = f, threshold = x) {
  nm <- rbinom(1, people, 0.5)
  sum(exp(c(rnorm(nm, m[1], m[2]), rnorm(people - nm, f[1], f[2])))) > x
}

sims <- replicate(1E5, cable(10, male = m, female = f, threshold = x))

# probability the cable breaks
table(sims)[[2]] / 1E5
```

### Question 3

```{r arm07-q03}
widget <- c(5, 4)
market <- c(4E4, 1E4)

savings <- function(widget, market) {
  rnorm(1, widget[1], widget[2]) * round(rnorm(1, market[1], market[2]))
}

sims <- replicate(1E5, savings(widget, market))
mean(sims)
sd(sims)
qplot(sims, bins = 50)
```

### Question 4

#### (a)

```{r arm07-q04a}
dat <- read_csv(str_c(arm_url, 'beauty/ProfEvaltnsBeautyPublic.csv'))

reg <- lm(courseevaluation ~ age + btystdave + female + nonenglish, data = dat)

xA <- c(1, 50, -1.0, 1, 0)
xB <- c(1, 60, -0.5, 0, 0)

n <- summary(reg)$df[1] + summary(reg)$df[2]
k <- summary(reg)$df[1]
beta_hat  <- summary(reg)$coefficients[, 1]
bcov_hat  <- summary(reg)$cov.unscaled
sigma_hat <- summary(reg)$sigma

insA <- rep(NA, 1000)
insB <- rep(NA, 1000)
for (s in 1:1000) {
  
  # predictive & parameter uncertainty
  sigma_sim <- sigma_hat * sqrt(n - k) / sqrt(rchisq(1, n - k))
  beta_sim  <- MASS::mvrnorm(1, beta_hat, sigma_sim ^ 2 * bcov_hat)
  
  # simulation
  insA[s] <- rnorm(1, sum(beta_sim * xA), sqrt(sigma_sim))
  insB[s] <- rnorm(1, sum(beta_sim * xB), sqrt(sigma_sim))
  
}
```

#### (b)

```{r arm07-q04b}
qplot(insA - insB, bins = 50)

# probability A > B
table(insA > insB)[2] / 1000
```